#!/usr/bin/env python3
"""Generate src/jambot/BotDictionary.h -- the real-word gate for typo repair.

BotLanguage repairs a word it does not recognise by looking for the nearest
lexicon entry within a small edit budget. That is only safe if we can tell a
mistyped word from an ordinary English one, and without that test the repair is
actively harmful: `chat` becomes `chart`, `room` becomes `root`, `oops` becomes
`loop`, and each produces a confident wrong answer rather than an honest
fallback.

Shipping a whole English dictionary would be a megabyte to answer a question we
only ever ask in one place. The only words that can change a repair decision are
the ones the repair could reach -- so this embeds exactly those: every English
word within the repair budget of some lexicon entry, plus a margin so that a
small edit to the lexicon does not silently uncover a word.

Source: SCOWL (Spell Checker Oriented Word Lists), Kevin Atkinson, via the
Debian `wbritish` package. Permissive with attribution; see THIRDPARTY.md.

Usage (from the repo root, after changing the lexicon):
    python3 scripts/make_wordlist.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = "/usr/share/dict/british-english"
OUT = os.path.join(ROOT, "src", "jambot", "BotDictionary.h")

# Must match BotLanguage.cpp: plain Damerau-Levenshtein, one edit up to five
# characters and two beyond. One extra edit of slack, so that adding or
# respelling a lexicon entry does not quietly drop a word out of the gate and
# reintroduce a wrong answer.
MARGIN = 1


def cost(a, b, ceiling):
    if abs(len(a) - len(b)) > 2:
        return 99
    prev2, prev = None, list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        cur = [i]
        for j, cb in enumerate(b, 1):
            best = min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (ca != cb))
            if i > 1 and j > 1 and a[i - 1] == b[j - 2] and a[i - 2] == b[j - 1]:
                best = min(best, prev2[j - 2] + 1)
            cur.append(best)
        if min(cur) > ceiling:
            return 99
        prev2, prev = prev, cur
    return prev[-1]


def lexicon():
    src = open(os.path.join(ROOT, "src", "jambot", "BotLanguage.cpp"), encoding="ascii").read()
    words = set()
    for table in ("kLexicon", "kClassed"):
        m = re.search(r"const \w+ %s\[\] = \{(.*?)\n\};" % table, src, re.S)
        if not m:
            sys.exit("could not find %s in BotLanguage.cpp" % table)
        words |= set(re.findall(r'\{"([a-z]+)"', m.group(1)))
    # Entries under four characters are matched exactly and never repaired, so
    # nothing near them can change a decision.
    return sorted(w for w in words if len(w) >= 4)


def main():
    if not os.path.exists(SOURCE):
        sys.exit("no word list at %s (apt install wbritish)" % SOURCE)

    lex = lexicon()
    words = set()
    for line in open(SOURCE, encoding="utf-8", errors="ignore"):
        w = line.strip().lower()
        if w.isalpha() and w.isascii() and 2 <= len(w) <= 16:
            words.add(w)

    keep = []
    for w in sorted(words):
        budget = (1 if len(w) <= 5 else 2) + MARGIN
        for entry in lex:
            if cost(w, entry, budget) <= budget:
                keep.append(w)
                break

    # MSVC caps a string literal at 65535 bytes, so the list is chunked.
    chunks, current = [], ""
    for w in keep:
        if len(current) + len(w) + 1 > 16000:
            chunks.append(current)
            current = ""
        current += w + " "
    if current:
        chunks.append(current)

    with open(OUT, "w", encoding="ascii") as f:
        f.write(HEADER % (len(lex), len(keep), len(chunks)))
        for c in chunks:
            f.write('    "%s",\n' % c.strip())
        f.write(FOOTER)
    print("%d lexicon entries -> %d words, %d chunks, %d bytes"
          % (len(lex), len(keep), len(chunks), sum(len(c) for c in chunks)))


HEADER = '''#pragma once

// GENERATED by scripts/make_wordlist.py -- do not edit.
//
// The real-word gate for BotLanguage's typo repair: a word that is ordinary
// English is not a mistyped one. Without this test, repair turns `chat` into
// `chart`, `room` into `root` and `oops` into `loop`, and each of those is a
// confident wrong answer where the honest one was a fallback.
//
// This is not a whole dictionary. It is exactly the English words that lie
// within the repair budget of one of the %d lexicon entries long enough to be
// repaired at all, plus one edit of margin -- %d words. Everything else could
// never have changed a decision, so carrying it would be a megabyte spent to
// answer a question nobody asks.
//
// Source: SCOWL (Spell Checker Oriented Word Lists), Copyright 2000-2011 Kevin
// Atkinson. Permissive with attribution; see THIRDPARTY.md. Regenerate with
// `python3 scripts/make_wordlist.py` after changing kLexicon.

#include <cstddef>
#include <string>
#include <unordered_set>

namespace BotDictionary {

// %d chunks: MSVC caps a single string literal at 65535 bytes.
inline const char *const *chunks(std::size_t &count) {
  static const char *const kChunks[] = {
'''

FOOTER = '''  };
  count = sizeof(kChunks) / sizeof(kChunks[0]);
  return kChunks;
}

inline bool isWord(const std::string &w) {
  static const std::unordered_set<std::string> kWords = [] {
    std::unordered_set<std::string> s;
    std::size_t count = 0;
    const char *const *c = chunks(count);
    for (std::size_t i = 0; i < count; ++i) {
      std::string current;
      for (const char *p = c[i]; *p; ++p) {
        if (*p == ' ') {
          if (!current.empty())
            s.insert(current);
          current.clear();
        } else {
          current += *p;
        }
      }
      if (!current.empty())
        s.insert(current);
    }
    return s;
  }();
  return kWords.count(w) != 0;
}

} // namespace BotDictionary
'''

if __name__ == "__main__":
    main()
